version: '3.7'
services:
    boilerplate:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
         - .:/usr/app/
         - /usr/app/node_modules
        image: boilerplate
        container_name: boilerplate
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - NODE_ENV=development    